# Generated by Django 2.2 on 2021-04-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='post_topic',
        ),
    ]
