# Generated by Django 2.2 on 2021-03-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
