# Generated by Django 2.2 on 2021-03-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0002_topic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
