# Generated by Django 2.2 on 2021-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0003_auto_20210312_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
