# Generated by Django 2.2 on 2021-07-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0003_auto_20210415_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-id']},
        ),
    ]
