# Generated by Django 2.2 on 2021-03-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0004_auto_20210314_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
