# Generated by Django 2.2 on 2021-04-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0006_topic_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-id']},
        ),
    ]
