# Generated by Django 2.2 on 2021-04-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0007_auto_20210412_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='post_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
