# Generated by Django 2.2 on 2021-04-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_posts', '0008_auto_20210413_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='post_entry',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
